name: test-connection

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Set environment (alpha, dev, staging)'
        required: true
        default: 'alpha'

  push:
    branches:
      - 'feature/OPS-1595-*'

env:
  SSH_USERNAME: ubuntu
  SSH_PORT: 22
  FOLDER_PATH: /home/c8prod/captiv8.io

jobs:
  build:
    name: post-update-cmd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: 35.179.74.229
          SSH_PORT: ${{ env.SSH_PORT }}
          SSH_USER: ${{ env.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd
      - run: ssh ${{ steps.ssh.outputs.SERVER }} ls
      - run: ssh ${{ steps.ssh.outputs.SERVER }} whoami
      - run: ssh ${{ steps.ssh.outputs.SERVER }} date
