name: Expose variables

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        description: 'Environment name'
        required: true
    outputs:
      DEPLOY_TO:
        description: "SSH host to deploy backend to"
        value: ${{ jobs.set_vars.outputs.deploy_to }}
      FOLDER_PATH:
        description: "Folder path"
        value: ${{ jobs.set_vars.outputs.folder_path }}
      EC2IP:
        description: 'Ec2 host ip'
        value: ${{ jobs.set_vars.outputs.ec2_host }}

jobs:
  set_vars:
    environment: ${{ inputs.ENVIRONMENT }}

    runs-on: ubuntu-latest

    outputs:
      deploy_to: ${{ steps.export.outputs.deploy_to }}
      folder_path: ${{ steps.export.outputs.folder_path }}
      ec2_host: ${{ steps.export.outputs.ec2_host }}

    steps:
      - uses: kanga333/variable-mapper@master
        id: export
        with:
          key: ${{ inputs.ENVIRONMENT }}
          map: |
            {
             "alpha": {
                "deploy_to": "platform.alpha.captiv8.io",
                "node_env": "testing",
                "folder_path": "/home/c8prod/captiv8.io",
                "ec2_host": "35.179.74.229"
              },
              "dev": {
                "deploy_to": "platform.dev.captiv8.io",
                "node_env": "testing",
                "folder_path": "/home/c8prod/captiv8.io",
                "ec2_host": "35.179.74.229"
              },
              "staging": {
                "deploy_to": "platform.staging.captiv8.io",
                "node_env": "testing",
                "folder_path": "/home/c8prod/captiv8.io",
                "ec2_host": "35.179.74.229"
              }
            }
          export_to: log,output
